// ─────────────────────────────────────────────────────────────────────────────
// Provenance system
//
// Every figure rendered in the app must declare where it came from. There are
// six allowed kinds; the UI renders these as compact tags + a tooltip and an
// optional "show working" expandable.
//
// Rules (enforced by the <Stat> + <ProvenanceTag> components):
//   1. A figure with no provenance MUST NOT render a number — it renders "—"
//      with a "no source connected" tooltip. This prevents hallucinated values.
//   2. A figure marked tally-checked MUST pass its check at runtime — failures
//      log a console.warn so we can spot future drift.
// ─────────────────────────────────────────────────────────────────────────────

export type ProvenanceKind =
  | "raw" // raw data from a connected source, no transformation
  | "upload" // user-uploaded file (CSV/Parquet)
  | "live" // live integration (Azure repo / Databricks / Drive)
  | "model" // output of the trained model (metrics, scores)
  | "ml" // generic ML-derived (clustering, embeddings, etc.)
  | "rule" // deterministic heuristic rule (NBA derivation, thresholds)
  | "ai"; // generative AI (LLM-written narrative)

export type Provenance = {
  kind: ProvenanceKind;
  /** Human-readable origin, e.g. "Azure DevOps · cease.csv (1,200 rows)". */
  source: string;
  /** Plain-English formula or method. Required for tally checks to be useful. */
  formula?: string;
  /** Optional inputs that the consumer can render in a "show working" panel. */
  inputs?: Array<{ label: string; value: string | number }>;
  /** Optional runtime tally: returned value MUST equal the displayed value. */
  tally?: () => number | string;
};

export const PROVENANCE_LABELS: Record<ProvenanceKind, string> = {
  raw: "Raw data",
  upload: "Upload",
  live: "Live integration",
  model: "ML model",
  ml: "ML derived",
  rule: "Heuristic rule",
  ai: "AI generated",
};

export const PROVENANCE_DESCRIPTIONS: Record<ProvenanceKind, string> = {
  raw: "Direct value from a connected raw data source — no transformation applied.",
  upload: "Sourced from a file uploaded to the dataset library.",
  live: "Sourced from a live external integration (Azure DevOps, Databricks, Drive).",
  model: "Produced by the trained churn model (most recent successful run).",
  ml: "Derived using a machine-learning method (clustering, statistics, etc.).",
  rule: "Deterministic rule applied to the underlying data — fully reproducible.",
  ai: "Generated by an LLM. Treat as guidance, not as a measured fact.",
};

/** Verify a tally; logs a warning if mismatch (does not throw). */
export function verifyTally(
  displayed: number | string,
  prov: Provenance,
  context?: string,
): boolean {
  if (!prov.tally) return true;
  try {
    const expected = prov.tally();
    const ok = String(expected) === String(displayed);
    if (!ok) {
      console.warn(
        `[tally-mismatch] ${context ?? prov.source}: displayed=${displayed} expected=${expected}`,
      );
    }
    return ok;
  } catch (err) {
    console.warn(`[tally-error] ${context ?? prov.source}`, err);
    return false;
  }
}
